# Generated by Django 6.0 on 2026-01-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Ticket number from 1 to 500', unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('LOCKED', 'Locked'), ('SOLD', 'Sold')], default='AVAILABLE', max_length=20)),
                ('buyer_name', models.CharField(blank=True, help_text='Saint Name + Full Name', max_length=255, null=True)),
                ('buyer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
