# Generated by Django 6.1.1 on 2026-09-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0002_usermessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Góp ý của khách', 'verbose_name_plural': 'Danh sách góp ý của khách'},
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gửi'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Công khai'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message',
            field=models.TextField(verbose_name='Nội dung góp ý'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại'),
        ),
    ]
