# Generated by Django 6.1.1 on 2026-09-14 09:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0003_alter_usermessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.PositiveIntegerField(help_text='Seat number in the venue map', unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('LOCKED', 'Locked'), ('PENDING', 'Pending confirmation'), ('SOLD', 'Sold')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Thông tin liên hệ'),
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('amount', models.PositiveIntegerField()),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending confirmation'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('tickets', models.ManyToManyField(related_name='payment_orders', to='fundraising.ticket')),
            ],
            options={
                'verbose_name': 'Đơn thanh toán',
                'verbose_name_plural': 'Đơn thanh toán',
                'ordering': ['-created_at'],
            },
        ),
    ]
