# Generated by Django 6.1.1 on 2026-09-16 06:07

from django.db import migrations, models


def create_default_seat_prices(apps, schema_editor):
    seat_price = apps.get_model('fundraising', 'SeatPrice')
    defaults = {
        'A': 99000,
        'B': 89000,
        'C': 79000,
        'D': 79000,
        'E': 79000,
    }
    for seat_type, price in defaults.items():
        seat_price.objects.get_or_create(seat_type=seat_type, defaults={'price': price})


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0004_ticket_buyer_email_alter_ticket_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type', models.CharField(choices=[('A', 'Hạng A'), ('B', 'Hạng B'), ('C', 'Hạng C'), ('D', 'Hạng D'), ('E', 'Hạng E')], max_length=1, unique=True, verbose_name='Hạng ghế')),
                ('price', models.PositiveIntegerField(verbose_name='Giá vé')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Bảng giá vé',
                'verbose_name_plural': 'Bảng giá vé',
                'ordering': ['seat_type'],
            },
        ),
        migrations.RunPython(create_default_seat_prices, migrations.RunPython.noop),
    ]
