# Generated by Django 6.1.1 on 2026-09-16 06:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0005_seatprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['number'], 'verbose_name': 'Ghế/Vé', 'verbose_name_plural': 'Quản lý ghế & vé'},
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Số tiền'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='buyer_email',
            field=models.EmailField(max_length=254, verbose_name='Email người mua'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='buyer_name',
            field=models.CharField(max_length=255, verbose_name='Họ tên người mua'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='confirmation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Mã xác nhận'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xác nhận'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email người mua'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='buyer_name',
            field=models.CharField(blank=True, help_text='Saint Name + Full Name', max_length=255, null=True, verbose_name='Họ tên người mua'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại cũ'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian giữ ghế'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.PositiveIntegerField(help_text='Seat number in the venue map', unique=True, verbose_name='Số ghế nội bộ'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Còn trống'), ('LOCKED', 'Đang giữ'), ('PENDING', 'Chờ xác nhận'), ('SOLD', 'Đã bán')], default='AVAILABLE', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối'),
        ),
    ]
